### ISSUE TITLE
Rename test_async_session_maker to avoid pytest collection warning

### ISSUE THREAD

**Issue by willthefirst** [willthefirst/aimagain#51]
## Friction

`tests/fixtures.py` exposes a module-level `test_async_session_maker = async_sessionmaker(...)`. When any test file does `from tests.fixtures import test_async_session_maker`, pytest sees the `test_` prefix and tries to collect it as a test, producing:

```
PytestCollectionWarning: cannot collect 'test_async_session_maker' because it is not a function.
```

Anyone reusing the session maker in a new test file hits this warning and has to alias the import (`as session_maker`) to silence it. Repeats every time.

Concrete example: `tests/test_promote_admin.py` (introduced in PR #49) had to alias on import.

## Fix

Rename the module-level binding in `tests/fixtures.py` from `test_async_session_maker` to `async_test_sessionmaker` (or any name without a `test_` prefix). Update all callers in the same PR.

## Acceptance criteria

- [ ] `tests/fixtures.py` no longer exposes any module-level name with a `test_` prefix that isn't a function/class.
- [ ] All callers updated (search the repo for `test_async_session_maker`).
- [ ] `dev test` runs with no `PytestCollectionWarning` from this name.
- [ ] `dev lint` passes.

## Effort

Small (single rename + caller updates).

## Source

[PR #49 retro](https://github.com/willthefirst/bedlam-connect/pull/49).
